## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 1.4.1

os:
  - linux

arch:
  - amd64

notifications:
  email: false

after_success:
  - julia test/coverage.jl

jobs:
  include:
    - stage: "Documentation"
      julia: 1.4.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
