## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1.1

notifications:
  email: false

git:
  depth: 1

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

after_success:
  # push coverage results to Coveralls
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl
  - julia -e 'using Pkg; Pkg.add("Documenter"); cd(Pkg.dir("ExperimentalDesign")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("ExperimentalDesign")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ExperimentalDesign")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

  after_success:
  - if [[ $TRAVIS_JULIA_VERSION = 1.1 ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      julia --project=coverage/ -e 'using Pkg; Pkg.instantiate();
          using Coverage; Codecov.submit(Codecov.process_folder());
          Coveralls.submit(Coveralls.process_folder())';
    fi

jobs:
  include:
    - stage: "Test"
      script:
        - julia --project=./ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=./ test/runtests.jl
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip
